### ISSUE TITLE
Bilateral automatic segmentation bug. Segmentation works only for one of the knees

### ISSUE THREAD

**Issue by barma7** [ad12/DOSMA#47]
When using automatic segmentation ` qdess segment ` with a bilateral knee acquisition. If the volume contains both knees automatic segmentation works only on the first knee. **Note** that no errors are displayed from terminal, however the output mask has all zeros where the cartilage of the second knee is supposed to be, which is not correct.

As workaround for the current bug is to separate the knees beforehand and to process the two volumes separately.

**Comment by ad12** [comment]
Thanks for the question! Some segmentation methods normalize images using volumetric zero-mean, unit standard deviation normalization. The normalization factors may not be accurate when computed over the field-of-view in bilateral scans due to larger extent of negative space (i.e. no anatomy).

When using dosma from the command line, knees will have to be separated prior to processing. If using dosma as a library in a Python script, you can load the volume and slice at the midpoint.

```python
mv = DicomReader().load("/path/to/bilateral/dicoms")

mv1 = mv[:, :, :mv.shape // 2]  # first knee
mv2 = mv[:, :, mv.shape // 2:]  # second knee
```

Closing this issue for now, but feel free to reopen
